// THIS CONST USE FOR COLLISION OF CHARACTER
// syntax:  {CHARACTER_NAME}_{PROPERTY_TYPE}_{PROPERTY_NAME}_{ANIM} or C{CHARACTER_NAME}_{PROPERTY_TYPE}_{PROPERTY_NAME}

// ALL CHARACTER:
export const CHARACTER_VELOCITY = 120

// DEATH CHARACTER
// body size
export const DEATH_SCALE = 1.2
export const DEATH_BODY_HEIGHT = 60 
export const DEATH_BODY_WIDTH_IDLE = 30
export const DEATH_BODY_WIDTH_ATTACK = 100

// offset
export const DEATH_BODY_OFFSET_Y = 30
export const DEATH_BODY_OFFSET_X_IDLE = 90 
export const DEATH_BODY_OFFSET_X_IDLE_FLIP_X = 20 

// moving offset
export const DEATH_FLIPX_MOVING_OFFSET = 70

// SKELETON CHARACTER
// body size
export const SKELETON_BODY_WIDTH_IDLE = 30
export const SKELETON_BODY_WIDTH_ATTACK = 60
export const SKELETON_BODY_HEIGHT = 64

// body offset
export const SKELETON_BODY_OFFSET_X = 0
export const SKELETON_BODY_OFFSET_X_FLIP_X = 20
export const SKELETON_BODY_OFFSET_Y = 0

export const SKELETON_FLIPX_MOVING_OFFSET = 24


// DEMON CHARACTER
// body size
export const DEMON_BODY_WIDTH_IDLE = 60
export const DEMON_BODY_HEIGHT = 80

// body offset
export const DEMON_BODY_OFFSET_X = 50
export const DEMON_BODY_OFFSET_Y = 50
